[package]
name = "ssv_full_node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.17.3"
url = "2.3.1"
env_logger = "0.9.1"